name: jobs_flutter_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.7.2
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.2.2
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  carousel_slider: ^5.1.1
  flutter_markdown: ^0.7.7+1
  persistent_bottom_nav_bar_v2: ^5.0.2
  dio: ^5.8.0+1
  get_it: ^8.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.7.0
  intl: ^0.20.2
  get_storage: ^2.1.1
  heroicons: ^0.11.0
  form_field_validator: ^1.1.0
  intl_phone_field: ^3.2.0
  shimmer: ^3.0.0
  awesome_dialog: ^3.2.1
  awesome_snackbar_content: ^0.1.6
  country_codes: ^2.0.1
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2
  flutter_svg_provider: ^1.0.7
  expandable: ^5.0.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^6.0.0
  freezed: ^3.1.0
  json_serializable: ^6.4.0
  flutter_native_splash: ^2.2.13
  logger: ^2.6.0
  device_preview: ^1.1.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: '#03A9F4'
  color_dark: '#23A9F4'
  android_12:
    color_dark: '#23A9F4'
  web: false

flutter:
  assets:
    - assets/
  uses-material-design: true