// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCu8WSMwyGIA9yUPO4bWfk5YR76lSie_E',
    appId: '1:854238029120:web:467a1d2beac58bfea746a5',
    messagingSenderId: '854238029120',
    projectId: 'jobs-app001',
    authDomain: 'jobs-app001.firebaseapp.com',
    storageBucket: 'jobs-app001.firebasestorage.app',
    measurementId: 'G-MNNWN565N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDleq1BCUhqfE7jG-ErD3RHM2eL-hwj60E',
    appId: '1:854238029120:android:4d6a75e71e802d1fa746a5',
    messagingSenderId: '854238029120',
    projectId: 'jobs-app001',
    storageBucket: 'jobs-app001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Q2iClxe_RN745gmjbGfZVOUkbKy7sx0',
    appId: '1:854238029120:ios:714f3deee4b8b736a746a5',
    messagingSenderId: '854238029120',
    projectId: 'jobs-app001',
    storageBucket: 'jobs-app001.firebasestorage.app',
    iosBundleId: 'com.devsadeq.jobsFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Q2iClxe_RN745gmjbGfZVOUkbKy7sx0',
    appId: '1:854238029120:ios:714f3deee4b8b736a746a5',
    messagingSenderId: '854238029120',
    projectId: 'jobs-app001',
    storageBucket: 'jobs-app001.firebasestorage.app',
    iosBundleId: 'com.devsadeq.jobsFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCu8WSMwyGIA9yUPO4bWfk5YR76lSie_E',
    appId: '1:854238029120:web:f21d1d43f28c3ceba746a5',
    messagingSenderId: '854238029120',
    projectId: 'jobs-app001',
    authDomain: 'jobs-app001.firebaseapp.com',
    storageBucket: 'jobs-app001.firebasestorage.app',
    measurementId: 'G-B1TRDRZ4NB',
  );
}
